////////////////////////////////////////////////////////////////////////
// Class:       FlashExt
// Module Type: analyzer
// File:        FlashExt_module.cc
//
// Generated at Thu Sep 14 11:16:14 2017 by David Lorca Galindo using artmod
// from cetpkgsupport v1_11_00.
////////////////////////////////////////////////////////////////////////

#include "art/Framework/Core/EDAnalyzer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "canvas/Utilities/InputTag.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"

#include "lardataobj/RecoBase/Track.h"
#include "lardataobj/RecoBase/OpFlash.h"
#include "lardataobj/RecoBase/PFParticle.h"
#include "lardataobj/AnalysisBase/T0.h"
#include "lardataobj/AnalysisBase/CosmicTag.h"
#include "lardata/Utilities/AssociationUtil.h"

#include "bernfebdaq-core/Overlays/BernZMQFragment.hh"
#include "artdaq-core/Data/Fragments.hh"

#include "art/Framework/Services/Optional/TFileService.h"

#include "uboone/CRT/CRTProducts/CRTHit.hh"
#include "uboone/CRT/CRTProducts/CRTTrack.hh"
#include "uboone/CRT/CRTAuxFunctions.hh"

#include "TTree.h"
#include "TH1F.h"
#include "TH2F.h"
#include "TH3S.h"
#include "TProfile.h"
#include "TF1.h"
#include "TDatime.h"
#include <iostream>
#include <stdio.h>
#include <sstream>
#include <vector>
#include <map>
#include <utility>
#include <typeinfo>


namespace crt {
  class FlashExt;
}

class crt::FlashExt : public art::EDAnalyzer {
public:
  explicit FlashExt(fhicl::ParameterSet const & p);
  // The destructor generated by the compiler is fine for classes
  // without bare pointers or other resource use.

  // Plugins should not be copied or assigned.
  FlashExt(FlashExt const &) = delete;
  FlashExt(FlashExt &&) = delete;
  FlashExt & operator = (FlashExt const &) = delete;
  FlashExt & operator = (FlashExt &&) = delete;

  // Required functions.
  void analyze(art::Event const & e) override;

  // Selected optional functions.
  void beginJob() override;
  void endJob() override;

private:

  // Declare member data here.
  art::ServiceHandle<art::TFileService> tfs;

  uint32_t fEvtNum; //Number of current event                       
  uint32_t frunNum;                //Run Number taken from event  
  uint32_t fsubRunNum;             //Subrun Number taken from event 
  std::string  data_label_flash_;
  int verbose_;


  TTree*       fTree;
  TH1F* hFlashTimeDis;
  
  //for Tree
  uint32_t fTriTim_sec;
  uint32_t fTriTim_nsec;
  double fY;
  double fZ;
  double fPEflash;
  double fTimFla;
  double fAbsTimFla;
  int fbeam;
  //for Tree

};


crt::FlashExt::FlashExt(fhicl::ParameterSet const & p)
  :
  EDAnalyzer(p),
  data_label_flash_(p.get<std::string>("data_label_flash_")),
  verbose_(p.get<int>("verbose"))//,
 // More initializers here.
{
  fTree = tfs->make<TTree>("flash_tree","Flash_Tree");
  fTree->Branch("event", &fEvtNum, "event/I");
  fTree->Branch("beam", &fbeam, "beam/I");
  fTree->Branch("trigger_ts", &fTriTim_sec, "Time (s)/I");
  fTree->Branch("trigger_tns", &fTriTim_nsec, "Time (ns)/I");
  fTree->Branch("Y_reco", &fY, "Y (cm)/D");
  fTree->Branch("Z_reco", &fZ, "Z (cm)/D");
  fTree->Branch("N_PE", &fPEflash, "Photoelectrons/D");
  fTree->Branch("T_flash", &fTimFla, "Flash time w.r.t trigger (us)/D");
  fTree->Branch("Abs_T_flash", &fAbsTimFla, "Absolute flash time (ns)/D");
}

void crt::FlashExt::analyze(art::Event const & evt)
{
  // Implementation of required member function here.

  frunNum    = evt.run();
  fsubRunNum = evt.subRun();
  fEvtNum = evt.event();

  art::Timestamp evtTime = evt.time();
  auto evt_time_sec = evtTime.timeHigh();
  auto evt_time_nsec = evtTime.timeLow();
  fTriTim_sec = evtTime.timeHigh();
  fTriTim_nsec = evtTime.timeLow();
  
  //get Optical Flash
  art::Handle< std::vector<recob::OpFlash> > rawHandle_OpFlash;
  evt.getByLabel(data_label_flash_, rawHandle_OpFlash);
  
  std::vector<recob::OpFlash> const& OpFlashCollection(*rawHandle_OpFlash);
  if(verbose_==1){ 
    std::cout<<"  OpFlashCollection.size()  "<<OpFlashCollection.size()<<std::endl; 
    getchar();
  }
  //get Optical Flash

  for(std::vector<int>::size_type i = 0; i != OpFlashCollection.size(); i++) {//A

    recob::OpFlash my_OpFlash = OpFlashCollection[i];

    auto Timeflash = my_OpFlash.Time(); //in us from trigger time
    hFlashTimeDis->Fill(Timeflash);      
    
    fY = my_OpFlash.YCenter();
    fZ = my_OpFlash.ZCenter();
    fPEflash = my_OpFlash.TotalPE();
    fTimFla = my_OpFlash.Time();
    fAbsTimFla = (evt_time_sec*1e9) + evt_time_nsec + (Timeflash * 1000);
    fbeam = my_OpFlash.OnBeamTime();

    /*
    //    std::vector< double > pes = my_OpFlash.PEs();
    fPEflash=0;
    for (unsigned int j=0; j<32; j++){
      int pe = my_OpFlash.PE(j);
      //int pe = pes[j];
      fPEflash += pe;
      std::cout<<" pe:  "<<pe<<std::endl; 
    }
    */

    if(verbose_==1){ 
      std::cout.precision(19);
      std::cout<<" Run:  "<<frunNum<<std::endl; 
      std::cout<<" SubRun:  "<<fsubRunNum<<std::endl; 
      std::cout<<" Event:  "<<fEvtNum<<std::endl; 
      std::cout<<" Trigger second:  "<<fTriTim_sec<<std::endl; 
      std::cout<<" Trigger nanosecond:  "<<fTriTim_nsec<<std::endl; 
      std::cout<<" Flash time w.r.t Trigger (us):  "<<Timeflash<<std::endl; 
      std::cout<<" Flash time w.r.t Trigger (ns):  "<<Timeflash*1000<<std::endl; 
      std::cout<<" Absolute time of flash time (ns):  "<<fAbsTimFla<<std::endl; 
      std::cout<<" is beam::  "<<fbeam<<std::endl;
      std::cout<<" Total PE:  "<<fPEflash<<std::endl;  
      getchar();
    }
    
    fTree->Fill();
  }//A


}

void crt::FlashExt::beginJob()
{
  // Implementation of optional member function here.

  hFlashTimeDis = tfs->make<TH1F>("hFlashTimDis","hFlashTimDis",3500,-3500,3500);
  hFlashTimeDis->GetXaxis()->SetTitle("Flash Time w.r.t. trigger (us)");
  hFlashTimeDis->GetYaxis()->SetTitle("Entries/bin");

}

void crt::FlashExt::endJob()
{
  // Implementation of optional member function here.
}

DEFINE_ART_MODULE(crt::FlashExt)
